In [1]:
# Real World Example using Covid Data
#
# Objectives: 
#    Import a csv file containing covid testing results and data
#    Analyse the data using SQL, Python, and Pandas
#    Plot the results

In [2]:
# Data
#
# we will be using csv files from from https://covidclinicaldata.org/ 
#

In [3]:
import pandas as pd
import glob
from pandasql import sqldf
pysqldf = lambda q: sqldf(q, globals())

In [8]:
df = pd.read_csv('data/10-20_carbonhealth_and_braidhealth.csv')

In [9]:
pd.set_option('display.max_columns', None)

In [11]:
df.head(50)

,batch_date,test_name,swab_type,covid19_test_results,age,high_risk_exposure_occupation,high_risk_interactions,diabetes,chd,htn,cancer,asthma,copd,autoimmune_dis,smoker,temperature,pulse,sys,dia,rr,sats,rapid_flu_results,rapid_strep_results,ctab,labored_respiration,rhonchi,wheezes,days_since_symptom_onset,cough,cough_severity,fever,sob,sob_severity,diarrhea,fatigue,headache,loss_of_smell,loss_of_taste,runny_nose,muscle_sore,sore_throat,cxr_findings,cxr_impression,cxr_label,cxr_link
0,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,39,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
1,2020-10-20,COVID-19 PCR External Result,Nasal,Negative,56,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
2,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,35,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
3,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,37,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
4,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,42,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
5,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,46,False,False,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
6,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,45,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
7,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,42,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
8,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,61,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
9,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,48,False,False,False,False,False,False,False,False,False,False,36.50,79.0,NaN,NaN,NaN,96.0,NaN,NaN,NaN,False,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
10,2020-10-20,COVID-19 PCR External Result,Nasal,Negative,52,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
11,2020-10-20,COVID-19 PCR External Result,Nasal,Negative,22,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
12,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,44,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
13,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,44,True,True,False,False,False,False,False,False,False,False,37.60,NaN,NaN,NaN,NaN,NaN,Negative,NaN,False,False,False,False,2.0,False,NaN,True,False,NaN,True,True,True,False,False,False,False,False,NaN,NaN,NaN,NaN
14,2020-10-20,COVID-19 PCR External Result,Nasal,Negative,41,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
15,2020-10-20,COVID-19 PCR External Result,Nasal,Negative,54,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
16,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,35,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
17,2020-10-20,COVID-19 PCR External Result,Nasal,Negative,45,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
18,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,31,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
19,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,22,False,False,False,False,False,False,False,False,False,False,37.40,80.0,90.0,58.0,12.0,98.0,NaN,NaN,False,False,NaN,False,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
20,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,41,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
21,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,44,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
22,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,37,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
23,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,43,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
24,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,39,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
25,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,38,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
26,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,65,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
27,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,41,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
28,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,59,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
29,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,47,True,False,False,False,False,False,False,False,False,False,36.40,68.0,133.0,88.0,14.0,99.0,NaN,NaN,True,False,True,True,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
30,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,49,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
31,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,59,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
32,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,41,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
33,2020-10-20,COVID-19 PCR External Result,Nasal,Negative,64,False,NaN,False,False,True,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
34,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,63,False,False,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
35,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,48,False,True,False,False,False,False,True,False,False,False,36.75,74.0,111.0,74.0,14.0,97.0,NaN,NaN,False,False,False,False,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
36,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,23,False,False,False,False,False,False,False,False,False,False,37.15,90.0,131.0,76.0,14.0,98.0,NaN,NaN,False,False,False,False,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
37,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,56,False,True,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
38,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,40,False,False,False,False,False,False,False,False,False,False,NaN,72.0,NaN,NaN,19.0,97.0,NaN,NaN,NaN,False,NaN,NaN,2.0,False,NaN,False,False,NaN,False,False,True,False,False,True,True,False,NaN,NaN,NaN,NaN
39,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,37,False,False,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
40,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,35,False,False,False,False,False,False,False,False,False,False,36.40,80.0,121.0,78.0,12.0,98.0,NaN,NaN,True,False,True,True,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
41,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,54,False,False,False,False,True,False,False,False,False,True,36.30,91.0,NaN,NaN,NaN,97.0,NaN,NaN,NaN,False,NaN,NaN,1.0,True,Mild,False,True,Mild,True,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
42,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,64,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
43,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,45,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
44,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,32,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
45,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,33,False,False,False,False,False,False,False,False,False,False,36.65,76.0,107.0,68.0,13.0,100.0,NaN,NaN,False,False,False,False,1.0,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
46,2020-10-20,COVID-19 PCR External Result,Nasal,Negative,40,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
47,2020-10-20,Rapid COVID-19 PCR Test,Nasal,Negative,54,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN
48,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,33,False,True,False,False,False,False,True,False,False,False,36.60,68.0,134.0,87.0,14.0,99.0,NaN,NaN,NaN,False,NaN,NaN,3.0,False,NaN,False,False,NaN,False,False,False,False,False,True,False,True,NaN,NaN,NaN,NaN
49,2020-10-20,"SARS-CoV-2, NAA",Nasal,Negative,39,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,NaN,False,False,False,False,False,False,False,False,NaN,NaN,NaN,NaN

In [12]:
df.columns

Index(['batch_date', 'test_name', 'swab_type', 'covid19_test_results', 'age',
       'high_risk_exposure_occupation', 'high_risk_interactions', 'diabetes',
       'chd', 'htn', 'cancer', 'asthma', 'copd', 'autoimmune_dis', 'smoker',
       'temperature', 'pulse', 'sys', 'dia', 'rr', 'sats', 'rapid_flu_results',
       'rapid_strep_results', 'ctab', 'labored_respiration', 'rhonchi',
       'wheezes', 'days_since_symptom_onset', 'cough', 'cough_severity',
       'fever', 'sob', 'sob_severity', 'diarrhea', 'fatigue', 'headache',
       'loss_of_smell', 'loss_of_taste', 'runny_nose', 'muscle_sore',
       'sore_throat', 'cxr_findings', 'cxr_impression', 'cxr_label',
       'cxr_link'],
      dtype='object')

In [13]:
# get symptoms

In [14]:
df_symptoms = pysqldf("""
SELECT
    covid19_test_results, labored_respiration, rhonchi,
    wheezes, cough, cough_severity,
    fever, sob, sob_severity, diarrhea, fatigue, headache,
    loss_of_smell, loss_of_taste, runny_nose, muscle_sore,
    sore_throat
FROM
    df
""")

In [15]:
df_symptoms.head()

,covid19_test_results,labored_respiration,rhonchi,wheezes,cough,cough_severity,fever,sob,sob_severity,diarrhea,fatigue,headache,loss_of_smell,loss_of_taste,runny_nose,muscle_sore,sore_throat
0,Negative,NaN,NaN,NaN,0,None,NaN,0,None,0,0,0,0,0,0,0,0
1,Negative,NaN,NaN,NaN,0,None,NaN,0,None,0,0,0,0,0,0,0,0
2,Negative,NaN,NaN,NaN,0,None,NaN,0,None,0,0,0,0,0,0,0,0
3,Negative,NaN,NaN,NaN,0,None,NaN,0,None,0,0,0,0,0,0,0,0
4,Negative,NaN,NaN,NaN,0,None,NaN,0,None,0,0,0,0,0,0,0,0

In [16]:
# note that we have different data types, mixing text and numerical data.
# to describe all data types, set include='all' in the describe method
# by default, describe() will only summarize numerical data

In [17]:
df_symptoms.describe(include='all')

,covid19_test_results,labored_respiration,rhonchi,wheezes,cough,cough_severity,fever,sob,sob_severity,diarrhea,fatigue,headache,loss_of_smell,loss_of_taste,runny_nose,muscle_sore,sore_throat
count,7294,1963.0,723.000000,961.000000,7294.000000,178,3137.000000,7294.000000,82,7294.000000,7294.000000,7294.000000,7294.000000,7294.000000,7294.000000,7294.000000,7294.000000
unique,2,NaN,NaN,NaN,NaN,3,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Negative,NaN,NaN,NaN,NaN,Mild,NaN,NaN,Mild,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,7269,NaN,NaN,NaN,NaN,132,NaN,NaN,52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,0.0,0.428769,0.409990,0.021662,NaN,0.018170,0.009460,NaN,0.005895,0.029613,0.025638,0.001645,0.001097,0.022896,0.013847,0.027831
std,NaN,0.0,0.495243,0.492087,0.145586,NaN,0.133588,0.096807,NaN,0.076559,0.169530,0.158062,0.040530,0.033102,0.149581,0.116864,0.164500
min,NaN,0.0,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,0.0,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,0.0,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,0.0,1.000000,1.000000,0.000000,NaN,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,0.0,1.000000,1.000000,1.000000,NaN,1.000000,1.000000,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [18]:
# Exercise - what are the possible value types for covid19_test_results, cough_severity, and sob_severity?
# how could you answer this with SQL?
# how could you answer this with pandas?

In [19]:
# Analysis
#
# let's investigate the effect of fatigue on Covid Test Results

In [20]:
sql = """
SELECT
    *
FROM
    df_symptoms
WHERE
    fatigue = 1
"""

r = pysqldf(sql)

In [21]:
r.head()

,covid19_test_results,labored_respiration,rhonchi,wheezes,cough,cough_severity,fever,sob,sob_severity,diarrhea,fatigue,headache,loss_of_smell,loss_of_taste,runny_nose,muscle_sore,sore_throat
0,Negative,0.0,0.0,0.0,0,None,1.0,0,None,1,1,1,0,0,0,0,0
1,Negative,0.0,NaN,NaN,0,None,0.0,0,None,0,1,0,0,0,0,0,0
2,Negative,0.0,0.0,0.0,1,Mild,0.0,1,None,1,1,0,0,0,0,1,0
3,Negative,0.0,0.0,0.0,0,None,0.0,0,None,0,1,1,0,0,0,0,1
4,Negative,0.0,NaN,NaN,0,None,0.0,0,None,0,1,0,0,0,0,0,1

In [22]:
# we can now get results only for test results where the patient indicated fatigue

In [23]:
r.describe()

,labored_respiration,rhonchi,wheezes,cough,fever,sob,diarrhea,fatigue,headache,loss_of_smell,loss_of_taste,runny_nose,muscle_sore,sore_throat
count,194.0,83.000000,102.000000,216.000000,214.000000,216.000000,216.000000,216.0,216.000000,216.000000,216.000000,216.000000,216.000000,216.000000
mean,0.0,0.313253,0.313725,0.305556,0.149533,0.162037,0.087963,1.0,0.472222,0.023148,0.032407,0.208333,0.314815,0.375000
std,0.0,0.466636,0.466298,0.461712,0.357449,0.369341,0.283899,0.0,0.500387,0.150723,0.177491,0.407060,0.465521,0.485247
min,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.0,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.0,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [24]:
# exercise - generate summary statistics for other possible predictors.
# note - you may want to go back and modify the original query
# for example, you might want to consider high risk occupations, contacts, or ER referrals

In [25]:
# Using GROUP BY queries
#
# we can use a SQL query to investigate the relationshop between covid test results and one or more symptoms

In [26]:
# single variable case
pysqldf("""
SELECT 
    covid19_test_results, COUNT(covid19_test_results)
FROM
    df_symptoms
GROUP BY 
    covid19_test_results
""")

  covid19_test_results  COUNT(covid19_test_results)
0             Negative                         7269
1             Positive                           25

In [27]:
# grouping on multiple variables
pysqldf("""
SELECT 
    covid19_test_results, fatigue, COUNT(covid19_test_results)
FROM
    df_symptoms
GROUP BY 
    covid19_test_results, fatigue
""")

  covid19_test_results  fatigue  COUNT(covid19_test_results)
0             Negative        0                         7056
1             Negative        1                          213
2             Positive        0                           22
3             Positive        1                            3

In [28]:
# Exercise - Does this data set show a higher probability for a positive test result 
# for patients reporting fatigue?

In [24]:
# Exercise - write use queries to find symptoms or other predictors (or combinations of them)

In [25]:
# Question (more to consider than answer). What are the odds of a positive result for someone reporting
# all measured symptoms. Can you answer this with SQL?