In [1]:
# Treating a pandas dataframe as a SQL table
#
# Objectives: 
#    Use the pandasql module to run queries on pandas dataframes

In [3]:
!pip install pandasql

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pandasql
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/6b/c4/ee4096ffa2eeeca0c749b26f0371bd26aa5c8b611c43de99a4f86d3de0a7/pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy in c:\users\houdi\anaconda3\lib\site-packages (from pandasql) (1.24.3)
Requirement already satisfied: pandas in c:\users\houdi\anaconda3\lib\site-packages (from pandasql) (2.0.3)
Requirement already satisfied: sqlalchemy in c:\users\houdi\anaconda3\lib\site-packages (from pandasql) (2.0.23)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\houdi\anaconda3\lib\site-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\houdi\anaconda3\lib\site-packages (from pandas->pandasql) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\houdi\anaconda3\lib\site-packages (from pandas->pandasql) (2023.3)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\houdi\anaconda3\lib\site-packages (from sqlalchemy->pandasql) (4.8.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\houdi\anaconda3\lib\site-packages (from sqlalchemy->pandasql) (2.0.1)
Requirement already satisfied: six>=1.5 in c:\users\houdi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.16.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py): started
  Building wheel for pandasql (setup.py): finished with status 'done'
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26800 sha256=bfba9f9b88332a466c09bb6a7b5649a0edd57b2312df7bfee6f6adc2d5e6df65
  Stored in directory: c:\users\houdi\appdata\local\pip\cache\wheels\e0\93\ec\110dcc8f0f4f92ba2d1cecdb3d14e0d6f7c8d21473bd629ad4
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [4]:
import pandas as pd
import pandasql
from pandasql import sqldf

In [5]:
# a short helper function so you don't have to specify locals or globals every time you run a query
pysqldf = lambda q: sqldf(q, globals())

In [7]:
species_df = pd.read_csv("data/species.csv")

In [8]:
# you can now run sql statements using a dataframe as a table name, without having to create a database

In [10]:
pysqldf("SELECT * FROM species_df LIMIT 15")

   species_id             genus          species     taxa
0          AB        Amphispiza        bilineata     Bird
1          AH  Ammospermophilus          harrisi   Rodent
2          AS        Ammodramus       savannarum     Bird
3          BA           Baiomys          taylori   Rodent
4          CB   Campylorhynchus  brunneicapillus     Bird
5          CM       Calamospiza      melanocorys     Bird
6          CQ        Callipepla         squamata     Bird
7          CS          Crotalus       scutalatus  Reptile
8          CT     Cnemidophorus           tigris  Reptile
9          CU     Cnemidophorus        uniparens  Reptile
10         CV          Crotalus          viridis  Reptile
11         DM         Dipodomys         merriami   Rodent
12         DO         Dipodomys            ordii   Rodent
13         DS         Dipodomys      spectabilis   Rodent
14         DX         Dipodomys              sp.   Rodent

In [11]:
surveys_df = pd.read_csv('data/surveys.csv')

In [12]:
# The result of a pandasql operation on a dataframe is a datframe. 
# So you can switch back and forth between the two

In [13]:
df_taxa = pysqldf("SELECT * FROM species_df WHERE taxa = 'Bird'")

In [14]:
# you may want to reset the index

In [15]:
df_taxa.set_index('species_id', inplace=True)

In [16]:
df_taxa

                      genus          species  taxa
species_id
AB               Amphispiza        bilineata  Bird
AS               Ammodramus       savannarum  Bird
CB          Campylorhynchus  brunneicapillus  Bird
CM              Calamospiza      melanocorys  Bird
CQ               Callipepla         squamata  Bird
PC                   Pipilo        chlorurus  Bird
PG                Pooecetes        gramineus  Bird
PU                   Pipilo           fuscus  Bird
SB                 Spizella          breweri  Bird
UP                   Pipilo              sp.  Bird
US                  Sparrow              sp.  Bird
ZL              Zonotrichia       leucophrys  Bird
ZM                  Zenaida         macroura  Bird